import re

log = """
 1:41.63 E Missing audit for Inflector:0.11.4 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for aead:0.5.2 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for aes:0.8.4 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for ahash:0.8.12 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for anyhow:1.0.100 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for ark-bls12-377:0.4.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for ark-bls12-381:0.4.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for ark-ec:0.4.2 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for ark-ff:0.4.2 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for ark-ff-asm:0.4.2 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for ark-ff-macros:0.4.2 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for ark-poly:0.4.2 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for ark-serialize:0.4.2 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for ark-serialize-derive:0.4.2 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for ark-std:0.4.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for array-bytes:6.2.3 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for arrayref:0.3.9 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for base16ct:0.2.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for base64ct:1.8.1 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for bitcoin-internals:0.2.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for bitcoin_hashes:0.13.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for bitvec:1.0.1 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for blake2:0.10.6 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for blake2b_simd:1.0.3 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for bounded-collections:0.2.2 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for bs58:0.5.1 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for byte-slice-cast:1.2.3 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for common-path:1.0.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for const-oid:0.9.6 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for constant_time_eq:0.3.1 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for crypto-bigint:0.5.5 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for crypto-mac:0.8.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for ctr:0.9.2 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for curve25519-dalek:4.1.3 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for curve25519-dalek-derive:0.1.1 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for der:0.7.10 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for derivative:2.2.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for derive-syn-parse:0.2.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for digest:0.9.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for docify:0.2.9 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for docify_macros:0.2.9 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for dyn-clonable:0.9.2 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for dyn-clonable-impl:0.9.2 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for dyn-clone:1.0.20 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for ecdsa:0.16.9 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for ed25519:2.2.3 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for ed25519-dalek:2.2.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for ed25519-zebra:4.0.3 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for elliptic-curve:0.13.8 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for environmental:1.1.4 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for expander:2.2.1 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for ff:0.13.1 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for file-guard:0.2.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for fixed-hash:0.8.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for funty:2.0.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for generic-array:0.14.9 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for getrandom_or_panic:0.0.3 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for group:0.13.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for hash-db:0.16.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for hash256-std-hasher:0.15.2 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for hashbrown:0.16.1 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for hex-conservative:0.1.2 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for hmac:0.8.1 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for hmac-drbg:0.3.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for impl-codec:0.6.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for impl-serde:0.4.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for impl-trait-for-tuples:0.2.3 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for indexmap:2.12.1 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for inout:0.1.4 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for integer-sqrt:0.1.5 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for itertools:0.11.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for k256:0.13.4 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for libsecp256k1:0.7.2 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for libsecp256k1-core:0.3.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for libsecp256k1-gen-ecmult:0.3.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for libsecp256k1-gen-genmult:0.3.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for memory-db:0.32.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for merlin:3.0.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for num-bigint:0.4.6 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for num-format:0.4.4 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for opaque-debug:0.3.1 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for parity-bip39:2.0.1 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for parity-scale-codec:3.6.12 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for parity-scale-codec-derive:3.7.5 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for password-hash:0.5.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for pbkdf2:0.12.2 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for pkcs8:0.10.2 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for polkavm-common:0.9.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for polkavm-derive:0.9.1 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for polkavm-derive-impl:0.9.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for polkavm-derive-impl-macro:0.9.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for prettyplease:0.2.37 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for primitive-types:0.12.2 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for proc-macro-crate:3.4.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for proc-macro2:1.0.103 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for quote:1.0.42 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for radium:0.7.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for ref-cast:1.0.25 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for ref-cast-impl:1.0.25 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for regex:1.12.2 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for regex-automata:0.4.13 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for regex-syntax:0.8.8 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for rfc6979:0.4.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for rustc-hex:2.1.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for scale-info:2.11.3 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.63 E Missing audit for scale-info-derive:2.11.6 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for schnellru:0.2.4 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for schnorrkel:0.11.5 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for sec1:0.7.3 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for secp256k1:0.28.2 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for secp256k1-sys:0.9.2 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for secrecy:0.8.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for serde:1.0.228 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for serde_core:1.0.228 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for serde_derive:1.0.228 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for serde_spanned:0.6.9 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for serdect:0.2.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for sha2:0.9.9 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for signal-hook-registry:1.4.7 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for signature:2.2.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for simple-mermaid:0.1.1 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for spki:0.7.3 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for ss58-registry:1.51.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for syn:2.0.111 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for thread_local:1.1.9 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for tokio:1.39.2 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for toml:0.8.23 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for toml_datetime:0.6.11 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for toml_datetime:0.7.5+spec-1.1.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for toml_edit:0.22.27 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for toml_edit:0.23.10+spec-1.0.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for toml_parser:1.0.6+spec-1.1.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for toml_write:0.1.2 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for tracing:0.1.44 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for tracing-attributes:0.1.31 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for tracing-core:0.1.36 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for tracing-subscriber:0.3.22 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for trie-db:0.29.1 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for trie-root:0.18.0 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for twox-hash:1.6.3 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for uint:0.9.5 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for valuable:0.1.1 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for w3f-bls:0.1.9 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for windows-link:0.2.1 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for windows-sys:0.61.2 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for wyz:0.5.1 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for zerocopy:0.8.31 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
 1:41.64 E Missing audit for zerocopy-derive:0.8.31 (requires ['safe-to-deploy']). Run `./mach cargo vet` for more information.
"""

pattern = re.compile(r"Missing audit for ([\w\-\.]+):([\w\.\+\-]+) \(requires \['safe-to-deploy'\]\)")

with open("supply-chain/config.toml", "a") as f:
    for line in log.splitlines():
        match = pattern.search(line)
        if match:
            crate = match.group(1)
            version = match.group(2)
            f.write(f"\n[[exemptions.{crate}]]\nversion = \"{version}\"\ncriteria = \"safe-to-deploy\"\n")
